### ISSUE TITLE
R crashes when using tidyr::unnest_wider

### ISSUE THREAD

**Issue by mattnolan001** [tidyverse/tidyr#1348]
Running tidyr::unnest_wider as part of a pipe, R crashes with the following error reported,
```
[91205:91206:20220410,071753.955164:ERROR file_io_posix.cc:148] open /home/matt/.r/crashpad_database/pending/dc2183c4-0851-4c62-908e-7d4e41a2702e.lock: File exists (17)
[91205:91205:20220410,071753.957703:ERROR process_memory_range.cc:86] read out of range
[91205:91205:20220410,071753.957712:ERROR elf_image_reader.cc:558] missing nul-terminator
[91205:91205:20220410,071753.957794:ERROR elf_dynamic_array_reader.h:61] tag not found
[91205:91205:20220410,071753.960132:ERROR elf_dynamic_array_reader.h:61] tag not found
[91205:91205:20220410,071753.960189:ERROR elf_dynamic_array_reader.h:61] tag not found
[91205:91205:20220410,071753.960236:ERROR elf_dynamic_array_reader.h:61] tag not found
[91205:91205:20220410,071753.960281:ERROR elf_dynamic_array_reader.h:61] tag not found
```

Further description and discussion here: https://stackoverflow.com/questions/71820155/r-crashes-when-using-tidyrunnest-wider

Here is a reproducible example (with thanks to Ben Bolker):
```r
library(tidyverse)
f <- function(n) tibble(neuron=0:(n-1), r.squared = rnorm(n),
     slope = rnorm(n), p.value = rnorm(n))
df <- replicate(1000, f(1000), simplify = FALSE)

dff <- tibble(x=df)
for (i in 1:100) { 
   cat(i, "\n")
   unnest_wider(dff, x)
}
```

**Comment by mattnolan001** [comment]
@lionel- A more reliable reprex is:
```
library(tidyverse)
f <- function(n) {
  df <- tibble(neuron=0:(n-1), r.squared = rnorm(n),
                        slope = rnorm(n), p.value = rnorm(n))
  df$p.value[2] <- NA
  df
}
df <- replicate(1000, f(1000), simplify = FALSE)

dff <- tibble(x=df)
for (i in 1:100) { 
  cat(i, "\n")
  unnest_wider(dff, x)
}
```

I've tested this with tidyr from CRAN and with tidtr 1.2.0.9000. It reliably crashes with both.

**Comment by DavisVaughan** [comment]
https://github.com/r-lib/vctrs/pull/1553 should fix this

**Comment by mattnolan001** [comment]
Is r-lib/vctrs/pull/1553 included in v1.2.0.9000? This is the number given for the version I just pullled from the main github repo and it still crashes.

**Comment by DavisVaughan** [comment]
You'd have to run `devtools::install_github("r-lib/vctrs#1553")`, then restart R. Then both CRAN tidyr and dev tidyr should work

**Comment by mattnolan001** [comment]
Thanks! That works now.

**Comment by lionel-** [comment]
The fix is now on CRAN, thanks for the reprex and report @mattnolan001 @bbolker!
